config/routes.rb
resources :point_settings, only: %i[index create destroy]

resources :point_management, only: :index do
  collection do
    post :user_points
    get 'user_point_log', to: 'point_management#user_point_log'
  end
end

resources :points

resources :point_lines, only: :destroy do
  get 'edit_entries', to: 'point_lines#edit_entries'
  post 'update_entries', to: 'point_lines#update_entries'
end

post 'points/new', to: 'points#new'

put 'edit_point_lines', to: 'point_apis#edit_point_lines', as: 'edit_point_lines'
post 'check_projects_by_wade', to: 'point_apis#check_projects_by_wade', as: 'check_projects_by_wade'
post 'check_projects_by_cherry', to: 'point_apis#check_projects_by_cherry', as: 'check_projects_by_cherry'

app/models/point_line.rb
class PointLine < ActiveRecord::Base
  include Redmine::SafeAttributes

  belongs_to :point
  belongs_to :user
  belongs_to :project

  validates :value, presence: true

  enum status_id: { pending: 0, confirm: 1, reject: 2, finish: 3 }, _prefix: true

  safe_attributes 'point_id',
                  'user_id',
                  'project_id',
                  'time_entry_ids',
                  'description',
                  'total_entries',
                  'value',
                  'convert_value',
                  'carry_value',
                  'status_id',
                  'user_unit',
                  'user_area',
                  'purple_no'

  serialize :time_entry_ids, Array

  after_create :set_time_entry_point_id

  after_destroy :empty_time_entry_point_id
  after_destroy :update_point_amount

  scope :without_reject, -> { where.not(status_id: self.status_ids['reject']) }

  def retrieve_time_entries
    ids = self.time_entry_ids
    TimeEntry.where(id: ids)
  end

  def update_values
    if self.status_id_pending?
      time_entries = self.retrieve_time_entries
      update_total_entries = time_entries.map(&:hours).reduce(:+)
      self.update(total_entries: update_total_entries)

      update_convert_value = self.value * self.total_entries
      self.update(convert_value: update_convert_value)

      unless self.convert_value.zero? && self.carry_value.nonzero?
        update_carry_value = point.carry_value_format(convert_value)
        self.update(carry_value: update_carry_value)
      end
    end
  end

  private

  def set_time_entry_point_id
    time_entries = self.retrieve_time_entries
    time_entries.update_all(point_id: self.point.id)
  end

  def empty_time_entry_point_id
    time_entries = self.retrieve_time_entries
    time_entries.update_all(point_id: nil)
  end

  def update_point_amount
    point_lines = self.point.lines
    amount = point_lines.map(&:carry_value).reduce(:+)
    self.point.amount = amount
  end
end

app/controllers/point_lines_controller.rb
class PointLinesController < ApplicationController
  before_action :find_point_line, only: :destroy
  before_action :find_point_line_from_entries, only: %i[edit_entries update_entries]

  def destroy
    @point_line.destroy
  end

  def edit_entries
    @time_entries = @point_line.retrieve_time_entries
    respond_to do |format|
      format.js
    end
  end

  def update_entries
    unpdated_entries = @point_line.time_entry_ids
    @point_line.safe_attributes = params[:point_line]
    updated_entries = @point_line.time_entry_ids
    destroy_entry_ids = unpdated_entries - updated_entries

    if destroy_entry_ids.any?
      empty_destroy_entry_point_id(destroy_entry_ids)
      @point_line.update_values
    end

    respond_to do |format|
      format.js { @destroy_entries = destroy_entry_ids }
    end
  end

  private

  def find_point_line
    @point_line = PointLine.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_point_line_from_entries
    @point_line = PointLine.find(params[:point_line_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def empty_destroy_entry_point_id(destroy_entry_ids)
    destory_entries = TimeEntry.where(id: destroy_entry_ids)
    destory_entries.update_all(point_id: nil)
  end
end

app/helpers/point_lines_helper.rb
module PointLinesHelper
  def link_to_remove_entry_lines(name, f, options = {})
    f.hidden_field(:_destroy) + link_to_function(name,
                                                 'remove_entry_lines(this)',
                                                 options)
  end

  def link_to_remove_entry_lines_new_record(name, options = {})
    link_to_function(name, 'remove_entry_lines_new_record(this)', options)
  end
end

app/views/point_lines/_edit_entries_modal.html.erb
<h3 class="title"><%= @point_line.project.name %></h3>

<%= form_for @point_line, url: point_line_update_entries_path(@point_line),
                          remote: true,
                          method: :post do |f| %>
  <fieldset class="box">
    <table>
      <tr>
        <th><%= l(:field_issue) %></th>
        <th><%= l(:field_spent_on) %></th>
        <th><%= l(:field_created_on) %></th>
        <th><%= l(:field_hours) %></th>
      </tr>
      <tbody>
        <% @time_entries.each_with_index do |entry, idx| %>
          <tr class="entry-line" id="line-<%= idx %>">
            <td><%= entry.issue.subject %></td>
            <td><%= entry.spent_on %></td>
            <td><%= entry.created_on.strftime('%F %T') %></td>
            <td><%= entry.hours.round(2) %></td>

            <% if @time_entries.count > 1 %>
              <td><%= link_to_remove_entry_lines "", f, class: 'icon icon-del' %></td>
            <% end %>

            <%= f.hidden_field :time_entry_ids, value: entry.id, multiple: true %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </fieldset>

  <p class="buttons">
    <%= submit_tag l(:button_update) %>
    <%= link_to_function l(:button_cancel), 'hideModal(this)' %>
  </p>
<% end %>

app/views/point_lines/_edit_entries_new_record_modal.html.erb
<h3 class="title"><%= point_line.project.name %></h3>

<form>
  <fieldset class="box">
    <table>
      <tr>
        <th><%= l(:field_issue) %></th>
        <th><%= l(:field_spent_on) %></th>
        <th><%= l(:field_created_on) %></th>
        <th><%= l(:field_hours) %></th>
      </tr>
      <tbody>
        <% time_entries = TimeEntry.where(id: point_line.time_entry_ids) %>
        <% time_entries.each do |entry| %>
          <tr class="entry-line line-<%= idx %>" id="entry-<%= entry.id %>">
            <td><%= entry.issue.subject %></td>
            <td><%= entry.spent_on %></td>
            <td><%= entry.created_on.strftime('%F %T') %></td>
            <td><%= entry.hours.round(2) %></td>

            <% if time_entries.count > 1 %>
              <td><%= link_to_remove_entry_lines_new_record '', class: 'icon icon-del' %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </fieldset>

  <p class="buttons">
    <%= link_to_function l(:button_update), "checkEntryStatus(this, #{idx})" %>
    <%= link_to_function l(:button_cancel), 'hideModal(this)' %>
  </p>
</form>

app/views/point_lines/edit_entries.js.erb
$('#ajax-modal').html('<%= escape_javascript(render partial: 'point_lines/edit_entries_modal') %>');
showModal('ajax-modal', 'auto');

app/views/point_lines/update_entries.js.erb
<% if @destroy_entries.any? %>
  storeDescData();
  storeSubjectAndDesc();
  window.onbeforeunload = null;
  location.reload(true);
<% else %>
  hideModal($('form.edit_point_line'));
<% end %>