config/routes.rb
resources :point_settings, only: %i[index create destroy]

resources :point_management, only: :index do
  collection do
    post :user_points
    get 'user_point_log', to: 'point_management#user_point_log'
  end
end

resources :points

resources :point_lines, only: :destroy do
  get 'edit_entries', to: 'point_lines#edit_entries'
  post 'update_entries', to: 'point_lines#update_entries'
end

post 'points/new', to: 'points#new'

put 'edit_point_lines', to: 'point_apis#edit_point_lines', as: 'edit_point_lines'
post 'check_projects_by_wade', to: 'point_apis#check_projects_by_wade', as: 'check_projects_by_wade'
post 'check_projects_by_cherry', to: 'point_apis#check_projects_by_cherry', as: 'check_projects_by_cherry'

app/controllers/point_management_controller.rb
class PointManagementController < ApplicationController
  before_action :authorize
  before_action :fetch_users, only: :index
  before_action :fetch_users_by_department_cf, only: :index
  before_action :fetch_users_by_district_cf, only: :index
  before_action :fetch_users_by_name, only: :index
  before_action :set_pagination_data, only: :index
  before_action :set_user_point_logs, only: :user_point_log

  helper :users
  include PointsHelper

  def index
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="UserPoints.xlsx"'
        @user_point_columns = user_point_columns
        @user_points = User.includes(:user_point)
                           .pluck(:firstname, :lastname, :value, :remark)
      }
    end
  end

  def user_points
    render_defaults(update_users_points, tab: :users)
  end

  def user_point_log; end

  private

  def authorize
    deny_access unless allow_setting_point_user?
  end

  def fetch_users
    @status = params[:status] || 1
    @users = User.logged.status(@status)
  end

  def render_defaults(errors, url_opts = {})
    render_points(
      errors,
      point_management_index_path(url_opts)
    )
  end

  def render_points(errors, url)
    if errors.present?
      flash[:notice] = l(:notice_successful_update)
      redirect_to url
    else
      render :index, notice: l(:notice_successful_update)
    end
  end

  def user_points_params
    params[:user_points]&.to_unsafe_h || {}
  end

  def update_users_points
    user_points_params.each_value do |user_points|
      user_points.each do |user_id, point|
        user_point = UserPoint.find_by(user_id: user_id)
        if user_point.present?
          update_user_point!(user_point, point[:value], point[:remark])
        elsif point[:value].present? || point[:remark].present?
          create_user_point!(user_id, point[:value], point[:remark])
        end
      end
    end
  end

  def update_user_point!(user_point, value, remark)
    if value.present? || remark.present?
      user_point_log = user_point.init_log(User.current)
      user_point_log.add_point_detail(user_point.user, user_point.value, value) if user_point.value.to_d != value.to_d
      user_point_log.add_remark_detail(user_point.user, user_point.remark, remark) if user_point.remark != remark
      user_point_log.save

      user_point.update(value: value, remark: remark)
    else
      true
    end
  end

  def create_user_point!(user_id, value, remark)
    if value.present? || remark.present?
      user = User.find_by(id: user_id)
      user_point = UserPoint.create(user: user, value: value, remark: remark)

      user_point_log = user_point.init_log(User.current)
      user_point_log.add_point_detail(user, nil, value) if value.present?
      user_point_log.add_remark_detail(user, nil, remark) if remark.present?
      user_point_log.save
    else
      true
    end
  end

  def fetch_users_by_department_cf
    return unless params[:dept].present?

    dept_cf = CustomField.find_by(type: 'UserCustomField', name: '单位')
    @users = @users.select { |user| user.custom_field_value(dept_cf).include? params[:dept] }
    @users = User.where(id: @users.map(&:id))
  end

  def fetch_users_by_district_cf
    return unless params[:dist].present?

    dist_cf = CustomField.find_by(type: 'UserCustomField', name: '区域')
    @users = @users.select { |user| user.custom_field_value(dist_cf).eql? params[:dist] }
    @users = User.where(id: @users.map(&:id))
  end

  def fetch_users_by_name
    query_name = params[:name]
    return unless query_name.present?

    converter = Tradsim::Converter.new(query_name)
    sim_name = converter.to_sim
    sim_name_users = @users.like(sim_name)
    trad_name = converter.to_trad
    trad_name_users = @users.like(trad_name)
    ids = (sim_name_users.ids + trad_name_users.ids).uniq

    @users = @users.where(id: ids)
  end

  def set_pagination_data
    @users_count = @users.count
    @users_page = Redmine::Pagination::Paginator.new @users_count, per_page_option, params['page']
    @_users = @users.offset(@users_page.offset).limit(@users_page.per_page).to_a
  end

  def set_user_point_logs
    user_point = UserPoint.find_by(user_id: params[:format])
    @user = User.find_by(id: params[:format])
    @user_point_logs = user_point.logs
  end

  def user_point_columns
    [
      '#',
      l(:field_firstname),
      l(:field_lastname),
      l('activerecord.attributes.user_point.value'),
      l('activerecord.attributes.user_point.remark'),
      l(:field_district),
      l(:field_department)
    ]
  end
end

app/helpers/point_management_helper.rb
module PointManagementHelper
  def user_dept_options_for_select
    dept_cf = CustomField.find_by(type: 'UserCustomField', name: '单位')
    dept_values = dept_cf.possible_values.unshift('')

    options_for_select(dept_values.map { |val| [val, val] }, params[:dept])
  end

  def user_dist_options_for_select
    dist_cf = CustomField.find_by(type: 'UserCustomField', name: '区域')
    dist_values = dist_cf.possible_values.unshift('')

    options_for_select(dist_values.map { |val| [val, val] }, params[:dist])
  end

  def user_point_to_strings(details)
    strings = []

    details.each do |detail|
      strings << content_tag('li', user_point_show_detail(detail), class: 'lines')
    end

    strings
  end

  def user_point_show_detail(detail)
    user = detail.user
    prop = detail.property
    old_value = detail.old_value
    value = detail.value
    value = l(:text_user_point_value_nil) if value.blank?
    value = content_tag('i', h(value))

    if old_value.nil?
      l("text_user_point_new_#{prop}", user: user, value: value).html_safe
    else
      old_value = l(:text_user_point_value_nil) if old_value.blank?
      old_value = content_tag('i', h(old_value))
      l("text_user_point_update_#{prop}", user: user, old: old_value, value: value).html_safe
    end
  end
end

app/views/point_management/_user_points.html.erb
<% if users.blank? %>
  <p class="nodata"><%= t('label_no_data') %></p>
<% else %>
  <%= form_tag (user_points_point_management_index_path), id: 'user_points' do %>
    <table class="list">
      <thead>
        <tr>
          <th><%= t('field_login') %></th>
          <th><%= t('field_firstname') %></th>
          <th><%= t('field_lastname') %></th>
          <th>
            <%= t('activerecord.attributes.user_point.value') %>
          </th>
          <th>
            <%= t('activerecord.attributes.user_point.remark') %>
          </th>
          <th>
            <%= t('activerecord.attributes.user_point.logs') %>
          </th>
        </tr>
      </thead>
      <tbody>
        <% users.each do |user| %>
          <tr>
            <td>
              <%= avatar(user, size: '14') %>
              <%= link_to user.login, edit_user_path(user) %>
            </td>
            <td><%= user.firstname %></td>
            <td><%= user.lastname %></td>
            <td>
              <%= text_field_tag "user_points[user_id][#{user.id}][value]", user.user_point&.value %>
            </td>
            <td>
              <%= text_field_tag "user_points[user_id][#{user.id}][remark]", user.user_point&.remark %>
            </td>
            <td>
              <% if user&.user_point&.logs.present? %>
                <%= link_to l(:label_user_point_log), user_point_log_point_management_index_path(user) %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= submit_tag t('button_apply') %>
    <span class="pagination"><%= pagination_links_full users_page, users_count %></span>
    <% other_formats_links do %>
      <span>
        <%= link_to 'XLSX', point_management_index_path(format: 'xlsx') %>
      </span>
    <% end %>
  <% end %>
<% end %>

app/views/point_management/_user_points_filter.html.erb
<%= form_tag(point_management_index_path, method: :get, id: 'users_form') do %>
  <fieldset>
    <legend><%= l(:label_filter_plural) %></legend>
    <label for='dept'><%= l(:field_department) %>:</label>
    <%= select_tag 'dept', user_dept_options_for_select, class: 'small', onchange: 'this.form.submit(); return false;' %>

    <label for='dist'><%= l(:field_district) %>:</label>
    <%= select_tag 'dist', user_dist_options_for_select, class: 'small', onchange: 'this.form.submit(); return false;' %>

    <label for='name'><%= l(:label_user) %>:</label>
    <%= text_field_tag 'name', params[:name], size: 30 %>

    <%= hidden_field_tag :tab, :users %>

    <%= submit_tag l(:button_search), class: 'small' %>
    <%= link_to l(:button_clear), point_management_index_path(tab: :users), class: 'icon icon-reload' %>
  </fieldset>
<% end %>

app/views/point_management/index.html.erb
<%= render partial: 'shared/point_tabs' %>

<%= render partial: 'user_points_filter' %>
<%= render partial: 'user_points', locals: { users: @_users, users_page: @users_page, users_count: @users_count } %>

app/views/point_management/user_point_log.html.erb
<h3 class="title">
  <%= @user.name %>
  <%= l(:label_user_point_log) %>
</h3>

<div id="history">
  <% @user_point_logs.each do |log| %>
    <div class="journal">
      <h4 class="note-header">
        <%= avatar(log.user) %>
        <%= authoring log.created_at, log.user, label: :label_updated_time_by %>
      </h4>

      <ul class="details point_history_style">
        <% user_point_to_strings(log.details).each do |string| %>
          <%= string %>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>